#datasource setup
spring:
  datasource:
  url: jdbc:mysql://localhost:3306/labo


  username: root
  password:

  # hibernate setup
jpa:
  hibernate:
  ddl-auto: create
  generate-ddl: true
  show-sql: true
  # profile setup
  profiles:
  active: api